# Setup
title:               blog.yui.codes
tagline:             'thought dump revolving around art+tech'
description:         'a blog containing mainly learning notes and thought dumps around art+tech and tech art'
url:                 https://blog.yui.codes
baseurl:             ''
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              yui
  url:               https://yui.codes
  email:             yui@yui.codes

# Gems
plugins:
  - jekyll-paginate

exclude:
  - example.md
